// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
class ScoreUpdate;
struct ScoreUpdateDefaultTypeInternal;
extern ScoreUpdateDefaultTypeInternal _ScoreUpdate_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ScoreUpdate* Arena::CreateMaybeMessage<::ScoreUpdate>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ScoreUpdate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ScoreUpdate) */ {
 public:
  inline ScoreUpdate() : ScoreUpdate(nullptr) {}
  ~ScoreUpdate() override;
  explicit PROTOBUF_CONSTEXPR ScoreUpdate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ScoreUpdate(const ScoreUpdate& from);
  ScoreUpdate(ScoreUpdate&& from) noexcept
    : ScoreUpdate() {
    *this = ::std::move(from);
  }

  inline ScoreUpdate& operator=(const ScoreUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScoreUpdate& operator=(ScoreUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ScoreUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScoreUpdate* internal_default_instance() {
    return reinterpret_cast<const ScoreUpdate*>(
               &_ScoreUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ScoreUpdate& a, ScoreUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(ScoreUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScoreUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScoreUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ScoreUpdate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ScoreUpdate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ScoreUpdate& from) {
    ScoreUpdate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ScoreUpdate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ScoreUpdate";
  }
  protected:
  explicit ScoreUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScoresFieldNumber = 1,
    kCharactersFieldNumber = 2,
  };
  // repeated int32 scores = 1;
  int scores_size() const;
  private:
  int _internal_scores_size() const;
  public:
  void clear_scores();
  private:
  int32_t _internal_scores(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_scores() const;
  void _internal_add_scores(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_scores();
  public:
  int32_t scores(int index) const;
  void set_scores(int index, int32_t value);
  void add_scores(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      scores() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_scores();

  // repeated string characters = 2;
  int characters_size() const;
  private:
  int _internal_characters_size() const;
  public:
  void clear_characters();
  const std::string& characters(int index) const;
  std::string* mutable_characters(int index);
  void set_characters(int index, const std::string& value);
  void set_characters(int index, std::string&& value);
  void set_characters(int index, const char* value);
  void set_characters(int index, const char* value, size_t size);
  std::string* add_characters();
  void add_characters(const std::string& value);
  void add_characters(std::string&& value);
  void add_characters(const char* value);
  void add_characters(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& characters() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_characters();
  private:
  const std::string& _internal_characters(int index) const;
  std::string* _internal_add_characters();
  public:

  // @@protoc_insertion_point(class_scope:ScoreUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > scores_;
    mutable std::atomic<int> _scores_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> characters_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ScoreUpdate

// repeated int32 scores = 1;
inline int ScoreUpdate::_internal_scores_size() const {
  return _impl_.scores_.size();
}
inline int ScoreUpdate::scores_size() const {
  return _internal_scores_size();
}
inline void ScoreUpdate::clear_scores() {
  _impl_.scores_.Clear();
}
inline int32_t ScoreUpdate::_internal_scores(int index) const {
  return _impl_.scores_.Get(index);
}
inline int32_t ScoreUpdate::scores(int index) const {
  // @@protoc_insertion_point(field_get:ScoreUpdate.scores)
  return _internal_scores(index);
}
inline void ScoreUpdate::set_scores(int index, int32_t value) {
  _impl_.scores_.Set(index, value);
  // @@protoc_insertion_point(field_set:ScoreUpdate.scores)
}
inline void ScoreUpdate::_internal_add_scores(int32_t value) {
  _impl_.scores_.Add(value);
}
inline void ScoreUpdate::add_scores(int32_t value) {
  _internal_add_scores(value);
  // @@protoc_insertion_point(field_add:ScoreUpdate.scores)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
ScoreUpdate::_internal_scores() const {
  return _impl_.scores_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
ScoreUpdate::scores() const {
  // @@protoc_insertion_point(field_list:ScoreUpdate.scores)
  return _internal_scores();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
ScoreUpdate::_internal_mutable_scores() {
  return &_impl_.scores_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
ScoreUpdate::mutable_scores() {
  // @@protoc_insertion_point(field_mutable_list:ScoreUpdate.scores)
  return _internal_mutable_scores();
}

// repeated string characters = 2;
inline int ScoreUpdate::_internal_characters_size() const {
  return _impl_.characters_.size();
}
inline int ScoreUpdate::characters_size() const {
  return _internal_characters_size();
}
inline void ScoreUpdate::clear_characters() {
  _impl_.characters_.Clear();
}
inline std::string* ScoreUpdate::add_characters() {
  std::string* _s = _internal_add_characters();
  // @@protoc_insertion_point(field_add_mutable:ScoreUpdate.characters)
  return _s;
}
inline const std::string& ScoreUpdate::_internal_characters(int index) const {
  return _impl_.characters_.Get(index);
}
inline const std::string& ScoreUpdate::characters(int index) const {
  // @@protoc_insertion_point(field_get:ScoreUpdate.characters)
  return _internal_characters(index);
}
inline std::string* ScoreUpdate::mutable_characters(int index) {
  // @@protoc_insertion_point(field_mutable:ScoreUpdate.characters)
  return _impl_.characters_.Mutable(index);
}
inline void ScoreUpdate::set_characters(int index, const std::string& value) {
  _impl_.characters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ScoreUpdate.characters)
}
inline void ScoreUpdate::set_characters(int index, std::string&& value) {
  _impl_.characters_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ScoreUpdate.characters)
}
inline void ScoreUpdate::set_characters(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.characters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ScoreUpdate.characters)
}
inline void ScoreUpdate::set_characters(int index, const char* value, size_t size) {
  _impl_.characters_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ScoreUpdate.characters)
}
inline std::string* ScoreUpdate::_internal_add_characters() {
  return _impl_.characters_.Add();
}
inline void ScoreUpdate::add_characters(const std::string& value) {
  _impl_.characters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ScoreUpdate.characters)
}
inline void ScoreUpdate::add_characters(std::string&& value) {
  _impl_.characters_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ScoreUpdate.characters)
}
inline void ScoreUpdate::add_characters(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.characters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ScoreUpdate.characters)
}
inline void ScoreUpdate::add_characters(const char* value, size_t size) {
  _impl_.characters_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ScoreUpdate.characters)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ScoreUpdate::characters() const {
  // @@protoc_insertion_point(field_list:ScoreUpdate.characters)
  return _impl_.characters_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ScoreUpdate::mutable_characters() {
  // @@protoc_insertion_point(field_mutable_list:ScoreUpdate.characters)
  return &_impl_.characters_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
